#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=12:00:00
#PBS -l vmem=31gb
#PBS -N tractseg
#PBS -V

#needed for bridges
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:p100:2

set -e
set -x

masks=`jq -r '.masks' config.json`

if [ ! $masks == null ]; then
	echo "STARTING TRAINING..."

	#python brainlife-utils/create_training_dataset.py
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_training_dataset.py
	singularity exec --nv docker://paoloavesani/docker-test \
                    bin/peaks_to_cnn \
                    -json brainlife-utils/brainlife_config_training.json
                    
	if [ -d 'final_output/' ]; then 
 		rm -r final_output
	fi

	mv output final_output
	mkdir weights
	mv final_output/*.npz weights/.
 	mv final_output/Hyperparameters.txt weights/.

	if [ -f 'weights/*.npz' ]; then 
		echo "Training completed."
	else 
		echo "Weights missing."
		exit 1
	fi
  
else
	echo "STARTING TEST..."
   
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_test_dataset.py
	singularity exec --nv docker://paoloavesani/docker-test \
                    bin/peaks_to_cnn \
                    -json brainlife-utils/brainlife_config_test.json
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/adjust_test_output.py
   
	if [ -z "$(ls -A -- "tractseg_output")" ]; then    
		echo "tractseg_output is empty."; 
		exit 1;
	else    
		echo "test done." 
	fi
fi   

