#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=12:00:00
#PBS -l vmem=31gb
#PBS -N tractseg
#PBS -V

set -x
set -e

python brainlife-utils/create_training_dataset.py
singularity exec --nv docker://paoloavesani/docker-test \
                    bin/peaks_to_cnn \
                    -json brainlife-utils/brainlife_config_training.json
mkdir weights
mv output/*.npz weights/.
mv output/Hyperparameters.txt weigths/.
